apiVersion: v1
appVersion: V1.0
description: 'Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.'
name: wac
version: 0.1.0
home: wac.zaakonline.nl
icon: wac.zaakonline.nl