apiVersion: v1
entries:
  postgresql:
  - apiVersion: v1
    appVersion: 11.7.0
    created: "2021-01-05T15:01:16.0719802Z"
    deprecated: true
    description: DEPRECATED Chart for PostgreSQL, an object-relational database management
      system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 00745b88e84403be696b7514c6e8c02710d81eb6074876b0700fa28fd47a9b43
    home: https://www.postgresql.org/
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    urls:
    - charts/postgresql-8.6.4.tgz
    version: 8.6.4
  wac:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-01-05T15:01:16.025533Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: cadc145f04cd96b039c2dfda073c5cd63e0e7fcc38eb1b9abe30a7b5da8b5360
    home: wac.zaakonline.nl
    icon: wac.zaakonline.nl
    name: wac
    urls:
    - wac-0.1.0.tgz
    version: 0.1.0
generated: "2021-01-05T15:01:16.0192541Z"
